"use client"

import { useState } from "react"
import {
  ArrowUpRight, Bell, BookOpen, CalendarDays, Check, ChevronDown, CircleHelp,
  CreditCard, FileText, GraduationCap, LayoutDashboard, Menu, MoreHorizontal,
  PanelLeftClose, Search, Settings, Sparkles, TrendingUp, Users, X,
} from "lucide-react"
import { announcements, courses, deadlines } from "@/lib/dashboard-data"

const navItems = [
  { label: "Overview", icon: LayoutDashboard },
  { label: "My courses", icon: BookOpen },
  { label: "Calendar", icon: CalendarDays },
  { label: "Assignments", icon: FileText, count: 3 },
]

function ProgressBar({ value }: { value: number }) {
  return <div className="h-2 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary transition-all" style={{ width: `${value}%` }} /></div>
}

export function Dashboard() {
  const [sidebarOpen, setSidebarOpen] = useState(false)
  const [activeNav, setActiveNav] = useState("Overview")
  const [period, setPeriod] = useState("This semester")

  return (
    <div className="min-h-screen bg-background text-foreground">
      <aside className={`fixed inset-y-0 left-0 z-30 flex w-[252px] flex-col border-r border-border bg-card px-4 py-5 transition-transform lg:translate-x-0 ${sidebarOpen ? "translate-x-0" : "-translate-x-full"}`}>
        <div className="flex items-center justify-between px-3">
          <div className="flex items-center gap-3"><div className="flex size-9 items-center justify-center rounded-xl bg-primary text-primary-foreground"><GraduationCap className="size-5" /></div><span className="text-[17px] font-semibold tracking-tight">acadly</span></div>
          <button onClick={() => setSidebarOpen(false)} className="rounded-lg p-2 text-muted-foreground hover:bg-muted lg:hidden" aria-label="Close navigation"><X className="size-4" /></button>
        </div>
        <div className="mt-10 flex flex-1 flex-col">
          <p className="px-3 text-[10px] font-semibold uppercase tracking-[0.16em] text-muted-foreground">Workspace</p>
          <nav className="mt-3 flex flex-col gap-1" aria-label="Main navigation">{navItems.map((item) => { const Icon = item.icon; const active = activeNav === item.label; return <button key={item.label} onClick={() => { setActiveNav(item.label); setSidebarOpen(false) }} className={`flex items-center justify-between rounded-xl px-3 py-2.5 text-sm font-medium transition-colors ${active ? "bg-secondary text-primary" : "text-muted-foreground hover:bg-muted hover:text-foreground"}`}><span className="flex items-center gap-3"><Icon className="size-[17px]" />{item.label}</span>{item.count && <span className="rounded-md bg-primary px-1.5 py-0.5 text-[10px] font-semibold text-primary-foreground">{item.count}</span>}</button> })}</nav>
          <p className="mt-9 px-3 text-[10px] font-semibold uppercase tracking-[0.16em] text-muted-foreground">Personal</p>
          <nav className="mt-3 flex flex-col gap-1" aria-label="Personal navigation"><button className="flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium text-muted-foreground hover:bg-muted hover:text-foreground"><CreditCard className="size-[17px]" />Payments</button><button className="flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium text-muted-foreground hover:bg-muted hover:text-foreground"><Settings className="size-[17px]" />Settings</button></nav>
        </div>
        <div className="rounded-2xl bg-secondary p-4"><div className="flex items-start justify-between"><div className="flex size-8 items-center justify-center rounded-lg bg-card text-primary"><Sparkles className="size-4" /></div><button aria-label="More options" className="text-muted-foreground"><MoreHorizontal className="size-4" /></button></div><p className="mt-3 text-sm font-semibold">Keep your momentum</p><p className="mt-1 text-xs leading-5 text-muted-foreground">You&apos;re on a 12-day study streak. Nice work.</p><div className="mt-3 h-1.5 rounded-full bg-card"><div className="h-full w-[72%] rounded-full bg-primary" /></div></div>
        <div className="mt-4 flex items-center gap-3 border-t border-border px-2 pt-4"><div className="flex size-9 items-center justify-center rounded-full bg-muted text-xs font-semibold text-muted-foreground">AS</div><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">Aarav Sharma</p><p className="truncate text-xs text-muted-foreground">Computer Science</p></div><ChevronDown className="size-4 text-muted-foreground" /></div>
      </aside>
      {sidebarOpen && <button className="fixed inset-0 z-20 bg-foreground/20 lg:hidden" onClick={() => setSidebarOpen(false)} aria-label="Close navigation overlay" />}

      <main className="lg:pl-[252px]"><header className="flex h-[72px] items-center justify-between border-b border-border bg-card/80 px-5 backdrop-blur md:px-8"><div className="flex items-center gap-3"><button onClick={() => setSidebarOpen(true)} className="rounded-lg p-2 text-muted-foreground hover:bg-muted lg:hidden" aria-label="Open navigation"><Menu className="size-5" /></button><div className="relative hidden w-64 md:block"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><input className="h-10 w-full rounded-xl border border-border bg-background pl-9 pr-3 text-sm outline-none placeholder:text-muted-foreground focus:border-primary" placeholder="Search anything..." aria-label="Search" /></div><button className="rounded-lg p-2 text-muted-foreground hover:bg-muted md:hidden" aria-label="Search"><Search className="size-5" /></button></div><div className="flex items-center gap-2 md:gap-4"><button className="relative rounded-xl p-2.5 text-muted-foreground hover:bg-muted" aria-label="Notifications"><Bell className="size-[18px]" /><span className="absolute right-2 top-2 size-1.5 rounded-full bg-primary ring-2 ring-card" /></button><div className="hidden h-6 w-px bg-border md:block" /><div className="flex items-center gap-2"><div className="flex size-8 items-center justify-center rounded-full bg-muted text-[11px] font-semibold text-muted-foreground">AS</div><span className="hidden text-sm font-medium md:block">Aarav</span><ChevronDown className="hidden size-4 text-muted-foreground md:block" /></div></div></header>

        <div className="mx-auto max-w-[1440px] px-5 py-7 md:px-8 md:py-9"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-sm font-medium text-primary">Monday, October 26, 2026</p><h1 className="mt-2 text-2xl font-semibold tracking-tight md:text-[30px]">Good morning, Aarav</h1><p className="mt-1.5 text-sm text-muted-foreground">Here&apos;s what&apos;s happening with your academic journey.</p></div><div className="flex items-center gap-2"><button className="flex items-center gap-2 rounded-xl border border-border bg-card px-3.5 py-2.5 text-sm font-medium shadow-sm hover:bg-muted"><CalendarDays className="size-4 text-muted-foreground" />View calendar</button><button className="flex items-center gap-2 rounded-xl bg-primary px-3.5 py-2.5 text-sm font-medium text-primary-foreground shadow-sm hover:opacity-90"><FileText className="size-4" />New note</button></div></div>

          <section className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Current GPA" value="3.84" detail="+0.12 from last term" icon={TrendingUp} positive /><StatCard label="Attendance" value="94%" detail="2 classes missed" icon={Check} positive /><StatCard label="Credits completed" value="68 / 120" detail="57% of your degree" icon={GraduationCap} /><StatCard label="Fees due" value="$420" detail="Due Nov 01, 2026" icon={CreditCard} alert /></section>

          <div className="mt-6 grid gap-6 xl:grid-cols-[minmax(0,1.35fr)_minmax(330px,0.65fr)]"><section className="rounded-2xl border border-border bg-card p-5 shadow-sm md:p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold">Academic performance</h2><p className="mt-1 text-sm text-muted-foreground">Your grades across enrolled courses</p></div><select value={period} onChange={(e) => setPeriod(e.target.value)} className="rounded-lg border border-border bg-background px-3 py-2 text-xs font-medium outline-none"><option>This semester</option><option>Last semester</option></select></div><div className="mt-6 flex h-44 items-end gap-3 border-b border-border px-1 sm:gap-5">{[72, 76, 74, 81, 79, 86, 84, 92, 88, 91, 89, 94].map((height, index) => <div key={index} className="group flex h-full flex-1 flex-col items-center justify-end gap-2"><div className={`relative w-full max-w-8 rounded-t-md transition-colors ${index % 3 === 2 ? "bg-primary/70" : "bg-secondary"} group-hover:bg-primary`} style={{ height: `${height}%` }}><span className="absolute -top-6 left-1/2 hidden -translate-x-1/2 text-[10px] font-semibold text-primary group-hover:block">{height}</span></div><span className="text-[10px] text-muted-foreground">{["Jun", "", "Aug", "", "Oct", "", "Dec", "", "Feb", "", "Apr", ""][index]}</span></div>)}</div><div className="mt-5 flex flex-wrap items-center gap-x-6 gap-y-2 text-xs text-muted-foreground"><span className="flex items-center gap-2"><span className="size-2 rounded-full bg-primary" />Performance index</span><span className="flex items-center gap-2"><span className="size-2 rounded-full bg-secondary" />Previous months</span><span className="ml-auto flex items-center gap-1 font-medium text-accent-foreground"><TrendingUp className="size-3.5" />Trending up</span></div></section>

            <section className="rounded-2xl border border-border bg-card p-5 shadow-sm md:p-6"><div className="flex items-start justify-between"><div><h2 className="font-semibold">Upcoming deadlines</h2><p className="mt-1 text-sm text-muted-foreground">Stay ahead of your coursework</p></div><button className="text-muted-foreground hover:text-foreground" aria-label="More deadlines"><MoreHorizontal className="size-5" /></button></div><div className="mt-5 flex flex-col gap-1">{deadlines.map((item) => <div key={item.title} className="flex gap-3 rounded-xl py-3"><div className={`mt-1.5 size-2 shrink-0 rounded-full ${item.urgent ? "bg-primary" : "bg-border"}`} /><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{item.title}</p><p className="mt-1 truncate text-xs text-muted-foreground">{item.course}</p></div><span className={`shrink-0 text-xs font-medium ${item.urgent ? "text-primary" : "text-muted-foreground"}`}>{item.due}</span></div>)}</div><button className="mt-3 flex w-full items-center justify-center gap-1.5 rounded-xl border border-border py-2.5 text-xs font-semibold text-muted-foreground hover:bg-muted hover:text-foreground">View all assignments<ArrowUpRight className="size-3.5" /></button></section></div>

          <div className="mt-6 grid gap-6 xl:grid-cols-[minmax(0,1.35fr)_minmax(330px,0.65fr)]"><section className="rounded-2xl border border-border bg-card p-5 shadow-sm md:p-6"><div className="flex items-center justify-between"><div><h2 className="font-semibold">Current courses</h2><p className="mt-1 text-sm text-muted-foreground">Fall 2026 · 4 active courses</p></div><button className="text-xs font-semibold text-primary hover:underline">See all courses</button></div><div className="mt-5 overflow-x-auto"><div className="min-w-[560px]"><div className="grid grid-cols-[1.5fr_0.8fr_0.7fr_1fr] gap-4 border-b border-border px-2 pb-3 text-[10px] font-semibold uppercase tracking-wider text-muted-foreground"><span>Course</span><span>Grade</span><span>Score</span><span>Progress</span></div><div className="flex flex-col">{courses.map((course) => <div key={course.code} className="grid grid-cols-[1.5fr_0.8fr_0.7fr_1fr] items-center gap-4 border-b border-border/70 px-2 py-4 last:border-0"><div className="flex items-center gap-3"><div className="flex size-9 items-center justify-center rounded-lg bg-secondary text-xs font-bold text-primary">{course.code.split(" ")[0]}</div><div><p className="text-sm font-medium">{course.name}</p><p className="mt-0.5 text-xs text-muted-foreground">{course.code}</p></div></div><span className="text-sm font-semibold">{course.grade}</span><span className="text-sm text-muted-foreground">{course.score}%</span><ProgressBar value={course.score} /></div>)}</div></div></div></section>

            <section className="rounded-2xl border border-border bg-card p-5 shadow-sm md:p-6"><div className="flex items-center justify-between"><div><h2 className="font-semibold">Announcements</h2><p className="mt-1 text-sm text-muted-foreground">From your department</p></div><button className="text-xs font-semibold text-primary hover:underline">View all</button></div><div className="mt-5 flex flex-col gap-4">{announcements.map((item) => <article key={item.title} className="border-l-2 border-primary pl-3"><div className="flex items-start justify-between gap-2"><h3 className="text-sm font-medium leading-5">{item.title}</h3><span className="shrink-0 text-[10px] text-muted-foreground">{item.date}</span></div><p className="mt-1.5 text-xs leading-5 text-muted-foreground">{item.body}</p></article>)}</div><button className="mt-6 flex items-center gap-2 text-xs font-semibold text-muted-foreground hover:text-foreground"><CircleHelp className="size-4" />Need help? Visit student support</button></section></div>
        </div></main>
    </div>
  )
}

function StatCard({ label, value, detail, icon: Icon, positive, alert }: { label: string; value: string; detail: string; icon: typeof TrendingUp; positive?: boolean; alert?: boolean }) {
  return <div className="rounded-2xl border border-border bg-card p-5 shadow-sm"><div className="flex items-center justify-between"><p className="text-sm text-muted-foreground">{label}</p><div className={`flex size-8 items-center justify-center rounded-lg ${alert ? "bg-secondary text-primary" : "bg-accent text-accent-foreground"}`}><Icon className="size-4" /></div></div><p className="mt-4 text-2xl font-semibold tracking-tight">{value}</p><p className={`mt-1 text-xs ${positive ? "text-accent-foreground" : alert ? "text-primary" : "text-muted-foreground"}`}>{detail}</p></div>
}
